#version 430 core
#extension GL_ARB_compute_shader: enable
#extension GL_NV_gpu_shader5: enable

layout( local_size_x = 64, local_size_y = 1, local_size_z = 1 ) in;

layout (std430, binding=1) buffer aBufferIndexSlab
{
  uint pixel[];
};

void main() {
  uint width = gl_NumWorkGroups.x * gl_WorkGroupSize.x;
  uint idx = gl_GlobalInvocationID.x + gl_GlobalInvocationID.y * width;
  pixel[idx] = 0;
}
