#version 430 core
#extension GL_NV_shader_buffer_load: enable
//#extension GL_ARB_compute_variable_group_size: enable
#extension GL_ARB_compute_shader: enable
#extension GL_NV_gpu_shader5: enable

#include "voxel.glsl"

uniform uint *volume;

layout( local_size_x = BRICK_DIAMETER, local_size_y = 1, local_size_z = 1 ) in;

void main() {
	ivec3 pos = ivec3(gl_GlobalInvocationID);
	float hd = float(BRICK_RADIUS);
	float d = distance(vec3(pos), vec3(hd)) - hd;

	voxel_set(volume, pos, d < 0.0);
}
