#version 430 core
#extension GL_NV_shader_buffer_load: enable

#extension GL_ARB_compute_shader: enable
#extension GL_NV_gpu_shader5: enable

#include "voxel.glsl"

layout (std430) buffer brickBuffer {
  BrickData bricks[];
};
uniform uint32_t brick_index;

layout( local_size_x = 1, local_size_y = 1, local_size_z = 1 ) in;

uniform uint val;

void main() {
	BrickData brick = bricks[brick_index];
	brick.data[gl_GlobalInvocationID.x] = val;
}
