#version 430 core
#extension GL_NV_shader_buffer_load: enable
#extension GL_ARB_compute_shader: enable
#extension GL_NV_gpu_shader5: enable

layout( local_size_x = 512 , local_size_y = 1, local_size_z = 1 ) in;

layout (std430, binding=1) buffer rayMaskBuffer {
  uint mask[];
};

uniform uvec3 dims;

void main() {
  uvec3 p = gl_GlobalInvocationID;
  uint idx = (
      p.x +
      p.y * dims.x +
      p.z * dims.x * dims.y
  );
  mask[idx] = 0;
}
