#ifndef __CORE_H
#define __CORE_H

#define VOLUME_DIMS 512
#define VOLUME_RADIUS VOLUME_DIMS/2

#define BRICK_DIAMETER 512
#define BRICK_RADIUS BRICK_DIAMETER / 2
#define BRICK_VOXEL_COUNT BRICK_DIAMETER*BRICK_DIAMETER*BRICK_DIAMETER


#define TOTAL_COMMAND_QUEUES 16

#define RENDER_STATIC 1
//#define RENDER_DYNAMIC 1

//#define FULLSCREEN

#endif
